FROM node:14

ENV NODE_ENV=
ENV TARANTOOL_PORT=
ENV TARANTOOL_HOST=
ENV TARANTOOL_USER_NAME=
ENV TARANTOOL_USER_PASSWORD=


RUN mkdir /www && mkdir /www/app
WORKDIR /www/app
COPY package.json .
RUN npm i
COPY . .
CMD ["npm", "start"]
